### PR TITLE
Fix count values on platform selection on the home page

### LINKED ISSUE #752: [C-860] "Total numbers" on Home don't get affected by platform selection
when selecting a platform, the "total numbers" on Home don't get affected

depending on which platforms are selected by the user, the total # should change

e.g. if only Discord is selected, you should see total members + total activities in Discord

<sub>From [SyncLinear.com](https://synclinear.com) | [C-860](https://linear.app/crowddotdev/issue/C-860/total-numbers-on-home-dont-get-affected-by-platform-selection)</sub>

### PR DESCRIPTION
**Pull request by peoray**
# Changes proposed ✍️
Fix count values on platform selection on the home page

### <samp>🤖 Generated by Copilot at b43a433</samp>

/claim #752

Added platform filter and improved loading indicator for dashboard widget header. The filter allows users to see platform-specific data, and the indicator shows the correct loading state for the total counts.
​Fixes #752 

### <samp>🤖 Generated by Copilot at b43a433</samp>

> _To show counts of members and acts_
> _We added a platform filter fact_
> _But the `app-loading` prop_
> _Needed a little swap_
> _To match the total data impact_

### <samp>🤖 Generated by Copilot at b43a433</samp>

*  Use `totalLoading` prop instead of `loading` prop for `app-loading` component in dashboard widget header to match total counts of activities and members ([link](https://github.com/CrowdDotDev/crowd.dev/pull/781/files?diff=unified&w=0#diff-c73dcfef3257e628345e2d77c634d5a440999368b2ddc1955008d8b911d77d1fL10-R10))
*  Pass `platform` filter from state to `ActivityService.list` and `MemberService.list` methods in dashboard store actions to get platform-specific counts of activities and members for dashboard widget header ([link](https://github.com/CrowdDotDev/crowd.dev/pull/781/files?diff=unified&w=0#diff-3229e811e36fcc52729fe2443f9ca14ae324f62b35ac2d6aaf15daf705b6bd1dL137-R158), [link](https://github.com/CrowdDotDev/crowd.dev/pull/781/files?diff=unified&w=0#diff-3229e811e36fcc52729fe2443f9ca14ae324f62b35ac2d6aaf15daf705b6bd1dL248-R291))

## Checklist ✅
- [x] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Review by joanagmaia — CHANGES_REQUESTED** [review]
Once again thanks so much for the contribution 😄 
Almost there! Just a couple remarks:
- [ ] Please fix eslint related issues. You can see that one of the build failed in PR
- [ ] What you updated in the `actions.js` file is good 👌 But I believe you are also missing for Conversation and Organizations. So the same way you updated for `getActivitiesCount` and `getMembersCount`, you should also update for `getConversationCount`, and `getOrganizationsCount`

**Comment by peoray** [comment]
@joanagmaia thanks for the feedback. 
Regarding conversation and organization, the issue only mentioned members and activities, hence why I worked on them only.

**Comment by joanagmaia** [comment]
> @joanagmaia thanks for the feedback. Regarding conversation and organization, the issue only mentioned members and activities, hence why I worked on them only.

You are right, it should have been better detailed, apologies for that. I'll take care of updating the issue description to make sure that it also contains for organizations and conversations.
All 4 should respond in the same way to the filters applied so I really think we should update for all of them at once
@jonathimer the issue is for all dashboard widgets right?

**Comment by peoray** [comment]
@joanagmaia I'm not sure how to use the conversation. Can you help? There's no visual representation

**Review by joanagmaia — COMMENTED** [review]
@peoray you are right Conversation does not have a visual representation, that's why it was commented. I missed that one, sorry about the confusion.
Could you undo the changes for Conversations? Other than that looks good to me for Members, Organizations and Activities. Once you undo for Conversations I'll approve it

**Comment by peoray** [comment]
@joanagmaia Resolved

**Review by joanagmaia — APPROVED** [review]
LGTM 🚀

**Pull request merged**
