### PR TITLE
fix: don't use discordapp.com for channel links

### PR DESCRIPTION
**Pull request by Lulalaby**
# Changes proposed ✍️

### What

Updated discord channel domain from discordapp.com to discord.com

### Why

The domain discordapp is obsolete since years, discord should be used instead

## Checklist ✅
- [ ] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [x] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Review by joanreyero — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution! 😍

However, some changes will still be needed to approve this. You left some URLs to change in `discordIntegrationService` and `discordThreadsRepliesHistorical`. I suggest finding all occurrences of `discordapp` using the editor. 😊

**Comment by Lulalaby** [comment]
done @joanreyero

**Comment by Lulalaby** [comment]
oh damn, the cdn link broke

**Comment by Lulalaby** [comment]
We good to go now.
The cdn still uses discordapp.com

**Comment by Lulalaby** [comment]
that pull request should be ready

**Comment by Lulalaby** [comment]
boop

**Comment by Lulalaby** [comment]
@joanreyero can we get this merged <3 also, could i get a hacktoberfest-accepted label maybe 😋

**Comment by Lulalaby** [comment]
ping

**Comment by Lulalaby** [comment]
Closing this as there is not a single activity/response from anyone, futhermore won't be using the platform due to removal of the free essential plan, which is way too weird

**Pull request closed without merging**
