### PR TITLE
Update member to contact in app

### PR DESCRIPTION
**Pull request by joanagmaia**
# Changes proposed ✍️

### <samp>🤖 Generated by Copilot at 313b981</samp>

This pull request renames `members` to `contacts` throughout the frontend and backend codebase to align with the HubSpot integration and to improve the clarity of the terminology for the users. It updates the translation files, the integration components, the automation config files, the filter options, the trigger options, the suggested tasks, the quickstart guide, and the error messages to use the term `contact` instead of `member`. It also updates the corresponding test files to reflect the changes.
​

### <samp>🤖 Generated by Copilot at 313b981</samp>

> _The app had a term to correct_
> _It was `member`, but now it's `contact`_
> _So they changed every file_
> _With a search and replace style_
> _And hoped that it wouldn't affect_

### <samp>🤖 Generated by Copilot at 313b981</samp>

*  Rename "members" to "contacts" in various places to reflect the new naming convention for the people in the community ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-c5b77be57ed9bb133d105a6963c072164c6e4c834c0bd7aec6cc2bdfd0a2d718L7-R12), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-09e89dcf7af9599067d28b93941d35a0cff34f0942c95f2becf9c4727c04ab2dL332-R333), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-e7e8904ad8a2839ffb4f79a5b830671858f703cb78c8dfaa222f2a232b5b3543L224-R225), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-33a09223972f0b37287a220826b4923c6cc4216f75957de973ec63bddefd65aeL39-R42), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L72-R74), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L145-R171), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L182-R182), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L208-R208), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L219-R222), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L303-R303), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L387-R388), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L438-R438), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L444-R444), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L457-R465), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L561-R561), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-29177a6b05b402fa38f9810dec54c27d2766c2c923b6cc66de32e647863366cfL83-R83), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-f05cbe01e75107ec8e37db917346ee0b77e52d6e39a2745f8fe1e01222387837L31-R31), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-514554dffd9401848737fa589cbe7d4510672f4a4970cf13b37802dfd40871b6L32-R39), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-514554dffd9401848737fa589cbe7d4510672f4a4970cf13b37802dfd40871b6L105-R105), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-277ffbe89d66e672128e3830c545d954d516d187f7e15e51374f63a6892806b0L11-R11), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-e2ef4c4cfd836c42d5d9305bfb8920729b1ac2076a16d0d9a1d431429732b038L12-R12), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-e2ef4c4cfd836c42d5d9305bfb8920729b1ac2076a16d0d9a1d431429732b038L40-R40), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-32d58cce45e264c59c94cc5020b714e56adb3599b4dc5523516ca08ca605dc87L91-R91), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-fa74540078daa38423a95271ada6663c4cf6e2416fb71c377b27a805fd65b8c3L5-R5), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-fa74540078daa38423a95271ada6663c4cf6e2416fb71c377b27a805fd65b8c3L14-R14), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-2fe7ff0bb4fb943d95f477f1fa7f6806eb4e6a72f093e7b62bc91f6263338f51L46-R46), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-2fe7ff0bb4fb943d95f477f1fa7f6806eb4e6a72f093e7b62bc91f6263338f51L52-R52), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9fadf507d3578bc89bf23ed0b1bc8302ad77b1b0ca52d83b08d51aad3781d0a7L125-R126), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-3bca2b7600cd34c916cd5dbf5377a78185d4c45e5b31ba520e384e888486f643L13-R13), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-8e05e49cbfa6bf46b39302e26c51b84e11d55ba17c9f3ff508744a619d8b7ffdL159-R159), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-77513545834520f61e7c2ed9ffae77f30d2dad20aae66683f36c0d1143e2ee7fL77-R77), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-13b66bf087d7a44e295acd5c1b2b1ce32a0a9cf9db4819763275dd70afeb5d85L5-R5), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-85099f2c580b619d51352ecb75b30bb1b28125e1c0bed395e08cbc5e28c698dbL68-R68), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-8389f95daa7d5d8549841d17c1b38ef3e7490e0de29d8d591b25518d2b5d2e5bL13-R13))
*  Update the quickstart guide for enriching a contact to link to the `contacts` page instead of the `members` page ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-33a09223972f0b37287a220826b4923c6cc4216f75957de973ec63bddefd65aeL39-R42))
*  Update the tooltip for the analytics dashboard to explain how to access the `contacts` page ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9ba9bffc669e5a3b99ce78a959864d5db1df507e60b6061f436191fb05bd2e87L438-R438))
*  Update the test files for the `taskRepository` and the `tenantService` to match the updated suggested tasks in `backend/src/database/initializers/suggested-tasks.json` ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-09e89dcf7af9599067d28b93941d35a0cff34f0942c95f2becf9c4727c04ab2dL332-R333), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-e7e8904ad8a2839ffb4f79a5b830671858f703cb78c8dfaa222f2a232b5b3543L224-R225))
*  Update the HubSpot integration settings component to add a label for the contact attributes option ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-514554dffd9401848737fa589cbe7d4510672f4a4970cf13b37802dfd40871b6L105-R105))
*  Update the dev.to integration component to add a description for monitoring articles from individual users ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-29177a6b05b402fa38f9810dec54c27d2766c2c923b6cc66de32e647863366cfL83-R83))
*  Update the GitHub integration component to add a message for requiring admin permissions to connect the integration ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-f05cbe01e75107ec8e37db917346ee0b77e52d6e39a2745f8fe1e01222387837L31-R31))
*  Update the HubSpot automation action component to add a label for syncing all members from the matching organizations ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-fa74540078daa38423a95271ada6663c4cf6e2416fb71c377b27a805fd65b8c3L14-R14))
*  Update the HubSpot automation action option file to add a description for the option to add a member to a HubSpot contacts list ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-9fadf507d3578bc89bf23ed0b1bc8302ad77b1b0ca52d83b08d51aad3781d0a7L125-R126))
*  Update the HubSpot automation paywall component to add a body for the paywall message ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1621/files?diff=unified&w=0#diff-3bca2b7600cd34c916cd5dbf5377a78185d4c45e5b31ba520e384e888486f643L13-R13))

## Checklist ✅
- [x] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Comment by peoray** [comment]
What's the motivation in changing members to contacts?

**Review by yeganathan18 — COMMENTED** [review]
quick question: Are we still going to work on the code using the `member` context, rather than as `contacts`? I believe the changes are only for the copy stuff

**Comment by yeganathan18** [comment]
Hey @peoray, we've switched "Members" to "Contacts" because our platform is expanding beyond just community members. Exciting new updates and changes are coming up early next year! 😛

**Comment by peoray** [comment]
That's awesome, well done to everyone involved

**Review by yeganathan18 — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
