### PR TITLE
Fix #1596 (Remove Loading Animation)

### LINKED ISSUE #1596: Remove loading animation
### Problem
If the user is already on some page, for example Organizations →  tapping Organizations over and over again keeps showing the loading banned at the top of the screen.

### Proposed solution
Add a validation to the router to prevent showing loading animation if current route and next route are the same. Animation is currently handled in `frontend/src/router/index.js`

### PR DESCRIPTION
**Pull request by Sranjan0208**
Added validation to the router to prevent showing loading animation

# Changes proposed ✍️
This pull request addresses the issue of displaying the loading animation even when the user navigates to the same route. To achieve this, I've added a condition to check if the destination route (to.name) is different from the current route (from.name). If they are the same, the loading animation won't be triggered.

### <samp>🤖 Generated by Copilot at ca9b2d6</samp>

Fixed a bug where the progress bar would show up when navigating to the same route in the frontend. Updated the logic in `frontend/src/router/index.js` to only start the progress bar when the route name changes.
​

### <samp>🤖 Generated by Copilot at ca9b2d6</samp>

> _`routeName` changes_
> _progress bar shows or hides_
> _autumn leaves falling_

### <samp>🤖 Generated by Copilot at ca9b2d6</samp>

*  Prevent progress bar from showing up when navigating to the same route ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1626/files?diff=unified&w=0#diff-2766750fe4e47e725d24427092ed92a78eca3bae6c3583646f0ce4228ae872f8L58-R58))

## Checklist ✅
- [x] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [x] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Review by joanagmaia — APPROVED** [review]
LGTM 🚀 
Will deploy it on monday 😄

**Comment by joanagmaia** [comment]
Just missing to fix the conflicts

**Comment by joanagmaia** [comment]
@Sranjan0208 could you just solve the conflicts so that I can merge 😄 ?

**Comment by joanagmaia** [comment]
Sorry again @Sranjan0208, was gonna merge this one now but Lint is failing. Can you run the npm run lint to check it out?

**Comment by joanagmaia** [comment]
Hey @Sranjan0208, in the root of `frontend` you can run `npm run lint` to check the files that need fixing. The lint frontend check is failing 😄

**Comment by Sranjan0208** [comment]
I ran "npm run lint", and made the necessary changes required. Can you check if it's working fine now. Thanks

**Pull request merged**
