### PR TITLE
Updated twitter logo

### LINKED ISSUE #1696: Update the Twitter logo to X
To Reproduce - 
Go to the footer of the website.

In the current version of the website the logo of Twitter is not updated.

Screenshot 2023-10-16 194706

### PR DESCRIPTION
**Pull request by vinfinity7**
Updated twitter logo form ```https://cdn-icons-png.flaticon.com/512/733/733579.png``` to ```https://vectorseek.com/wp-content/uploads/2023/07/Twitter-X-New-Logo-Vector-2.png``` at two instances , pin me more instances of twitter logo 
Fixes #1696 
### <samp>🤖 Generated by Copilot at 8568fc6</samp>

Updated the Twitter icons for the integration card and the Eagle Eye platform to use a higher-resolution and more consistent icon from icons8.com. This improves the visual appearance and quality of the frontend.
​

### <samp>🤖 Generated by Copilot at 8568fc6</samp>

> _`Twitter` icon changed_
> _From icons8.com site_
> _A crisp autumn leaf_

### <samp>🤖 Generated by Copilot at 8568fc6</samp>

*  Update Twitter icon for integration card and Eagle Eye platform ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1709/files?diff=unified&w=0#diff-ec4cc1cb9e76708fd1ceb4ec761c86155b638edb62156ec55b1388bbceca0c65L13-R13), [link](https://github.com/CrowdDotDev/crowd.dev/pull/1709/files?diff=unified&w=0#diff-63680fb6f25d207864f424c402abc68e1cef86e3a5233c2006dd4a60ca3609c3L40-R40))

## Checklist ✅
- [x] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Comment by vinfinity7** [comment]
@mattinannt you might wanna look into this

**Review by joanagmaia — CHANGES_REQUESTED** [review]
Hey! In twitter's integration configuration you are updating this to an icon, not an image, so it's' not rendering properly. Can you provide a valid image url or add it to the project directory?
Same thing for eagle eye logo.
There's also another place that will need update. You'll also need to add svg support in crowd-icons for twitter logo. That's still with the old one.

**Comment by vinfinity7** [comment]
> Hey! In twitter's integration configuration you are updating this to an icon, not an image, so it's' not rendering properly. Can you provide a valid image url or add it to the project directory? Same thing for eagle eye logo. There's also another place that will need update. You'll also need to add svg support in crowd-icons for twitter logo. That's still with the old one.

ohk ill do it by tommorow

**Comment by vinfinity7** [comment]
> Hey! In twitter's integration configuration you are updating this to an icon, not an image, so it's' not rendering properly. Can you provide a valid image url or add it to the project directory? Same thing for eagle eye logo. There's also another place that will need update. You'll also need to add svg support in crowd-icons for twitter logo. That's still with the old one.

Ive updated the icon to a png file @joanagmaia

**Pull request closed without merging**
