### PR TITLE
Add text-based filter in members page for Job title

### LINKED ISSUE #1241: [C-2038] "Job title" filter in Members list
### Describe the problem

Currently, there's no proper way to look for members with certain job titles.

### Describe the improvement

Add a new text-based filter - Job title - to Members list. Position in filters list: 3rd

Screenshot 2023-08-08 at 14 41 48

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2038](https://linear.app/crowddotdev/issue/C-2038/job-title-filter-in-members-list)</sub>

### PR DESCRIPTION
**Pull request by peoray**
# Changes proposed ✍️

### What
Fixes #1241

### <samp>🤖 Generated by Copilot at abef4fc</samp>

Added a new filter for job title to the member filters on the frontend. Modified `frontend/src/modules/member/config/filters/main.ts` to import and use the new filter configuration from `frontend/src/modules/member/config/filters/jobTitle/config.ts`.
​

### <samp>🤖 Generated by Copilot at abef4fc</samp>

> _Filter by `jobTitle`_
> _A new string attribute_
> _Autumn of careers_

### <samp>🤖 Generated by Copilot at abef4fc</samp>

*  Add a new filter for job title of members ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1438/files?diff=unified&w=0#diff-c23c4489c043c0defaed2a11be2b0aeb276690a372a5b1f7e33139ff537a7514R1-R24))
* Include the job title filter in the member filters object ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1438/files?diff=unified&w=0#diff-9764bba874a0ee03488cf483fab4b7144d11c402793e69730e1a5508f1451535L15-R20))

## Checklist ✅
- [ ] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Review by joanagmaia — CHANGES_REQUESTED** [review]
In `frontend/src/shared/modules/filters/services/custom-attributes.service.ts`
can you add an extra validation for filtering?
`.filter((attribute) => attribute.show && attribute.name !== 'jobTitle')`

We were actually already displaying jobTitle in our custom attributes. Without this modification the filter will appear twice on the list.

Sorry for the confusion

**Comment by peoray** [comment]
@joanagmaia updated :)

**Review by joanagmaia — APPROVED** [review]
LGTM 🚀

**Comment by joanagmaia** [comment]
Hey @peoray just merged 2 of your PRs 😄 
Can you resolve conflict so that I can also merge this one after? Thanks!

**Comment by peoray** [comment]
@joanagmaia resolved :)

**Review by joanagmaia — APPROVED** [review]
LGTM 🚀

**Pull request merged**
