### PR TITLE
Enhanced Contributing guidelines

### PR DESCRIPTION
**Pull request by Arcturus22**
# Changes Proposed

### What
Corrected grammar of Contributing file.

### CODE REVIEW

**Comment by Arcturus22** [comment]
@joanagmaia @sausage-todd 
Please review my PR and merge it. It is a documentation `Improvement` PR

**Comment by Arcturus22** [comment]
@loicsaintroch @joanagmaia @themarolt 
Please review my PR and merge it. Suggest if any changes.

**Comment by Arcturus22** [comment]
@loicsaintroch @joanagmaia @themarolt
Please review my PR and merge it. Suggest if any changes.

**Comment by Arcturus22** [comment]
@loicsaintroch @joanagmaia @themarolt 
Please review the PR. I have resolved the conflicts.

**Comment by joanagmaia** [comment]
Hey @Arcturus22!
Thanks for your interest in contributing! I don't see any file changes. Do you have everything committed and pushed?

**Comment by Arcturus22** [comment]
@joanagmaia 
I'm sorry, but it wasn't updated/pushed. I have pushed the changes now. Please review and merge it.
Suggest if any changes.

**Review by joanagmaia — APPROVED** [review]
LGTM

**Pull request merged**
