### PR TITLE
Error logging for weekly emails worker

### PR DESCRIPTION
**Pull request by epipav**
# Changes proposed ✍️
Better logging of the error for weekly emails worker before retry logic happens.

### <samp>🤖 Generated by Copilot at ab87d27</samp>

Improved error handling and logging for `weeklyAnalyticsEmailsWorker` in `nodejs/analytics` microservice. This helps to prevent email failures and track database issues.
​

### <samp>🤖 Generated by Copilot at ab87d27</samp>

> _When the database fails and the data is lost_
> _We don't give up, we don't pay the cost_
> _We log the errors and handle them well_
> _We send the emails with the `weeklyAnalyticsEmailsWorker`_

### <samp>🤖 Generated by Copilot at ab87d27</samp>

*  Log and retry errors in weekly analytics emails worker ([link](https://github.com/CrowdDotDev/crowd.dev/pull/811/files?diff=unified&w=0#diff-697ea4871953442b989256533e0a23185da4aa8cfb0ae3296326383d8e772477R37-R41))
*  Return error object from get analytics data function ([link](https://github.com/CrowdDotDev/crowd.dev/pull/811/files?diff=unified&w=0#diff-697ea4871953442b989256533e0a23185da4aa8cfb0ae3296326383d8e772477R527))

## Checklist ✅
- [ ] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [ ] Add screehshots to the PR description for relevant FE changes
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

**Review by joanreyero — APPROVED** [review]

**Comment by joanreyero** [comment]
Some of these copilot poems are awesome 😄

**Comment by epipav** [comment]
test

**Comment by epipav** [comment]
test3

**Comment by epipav** [comment]
test4

**Comment by epipav** [comment]
test7

**Review by gaspergrom — APPROVED** [review]

**Pull request merged**
